import React from 'react'

const ArticleText = () => {
    return (
        <article className="article text">

            <p>
                <span className="header">Mauris dignissm</span>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at urna ipsum. Ut pellentesque tincidunt neque, fermentum pharetra metus elementum et. Nulla in metus molestie, auctor nisi id, ornare risus. Quisque a justo a odio cursus viverra quis ut sem. Nullam nec lorem vitae ligula faucibus commodo at quis erat. Phasellus a odio vehicula, ultricies orci in, condimentum est. Nunc sit amet auctor libero. Morbi vitae nunc a neque sollicitudin suscipit. Suspendisse iaculis, orci a pretium pharetra, odio ex porta augue, vel ultrices leo tortor et tortor. In tristique, nisl vitae faucibus tempus, enim nulla elementum ex, vitae malesuada velit magna quis ipsum. Praesent nec sodales mauris. Curabitur et leo urna. Vestibulum dignissim, ante at cursus finibus, massa sapien euismod arcu, eget tincidunt risus justo sit amet ex.

                Maecenas convallis risus non fringilla vehicula. Etiam varius diam neque. In et ipsum ac felis vestibulum venenatis vitae nec diam. Vestibulum sit amet tellus vel nisl ornare elementum id egestas nisl. Integer justo dolor, ultrices in sem ut, cursus lacinia neque. Etiam metus odio, aliquet in luctus sed, cursus vel lectus. Nulla lorem eros, finibus quis nisi in, interdum feugiat est. Nunc tempor sit amet eros id placerat. Cras viverra tempor tincidunt. Duis risus magna, vehicula et augue eu, cursus pellentesque metus.

                Vestibulum velit augue, condimentum quis massa eget, aliquet pharetra risus. Curabitur pharetra nunc in congue aliquam. Quisque vel massa at augue interdum finibus. Donec tincidunt orci quis ante egestas, sit amet porttitor augue venenatis. Donec mattis, tellus at scelerisque posuere, mauris nisi blandit libero, quis tincidunt nulla enim in tortor. Suspendisse et pulvinar urna. Nunc erat metus, commodo non accumsan quis, porttitor facilisis est. Ut dignissim erat risus, vitae pulvinar enim auctor ac.
                
                <span className="header">Proin leo nunc molllis at</span>
                Integer tempus justo purus, vel finibus leo vulputate in. Mauris dignissim justo vel ligula imperdiet, sit amet facilisis felis ultrices. Mauris efficitur, mauris sed rhoncus dignissim, dolor erat maximus tortor, sed pellentesque mi enim in augue. Proin malesuada, ante ac scelerisque pharetra, erat arcu viverra magna, lobortis eleifend urna eros auctor erat. Donec vehicula sagittis elit, non faucibus mi rutrum non. Cras at accumsan tellus. Aenean vel ornare sem. Nunc ultrices nibh nunc, ac commodo diam accumsan nec. Ut id sem elementum risus vestibulum suscipit non quis eros. Praesent eget lorem quis enim porttitor pellentesque eget nec nisi. Praesent mattis est sit amet eros ultrices blandit. In pellentesque mauris nec risus rhoncus, nec gravida ex tristique. Curabitur lectus urna, hendrerit at congue nec, aliquet ut dolor. Vestibulum lorem est, feugiat at odio ut, vestibulum vulputate lorem. Proin leo nunc, mollis at neque volutpat, fermentum faucibus turpis.

                Sed ut lobortis justo. Curabitur ipsum enim, suscipit vel vestibulum sit amet, porttitor id tortor. Donec dolor arcu, elementum vulputate justo nec, congue dapibus ante. Etiam varius ut nisl quis dictum. Praesent finibus turpis massa, in ornare massa ornare pellentesque. Cras sagittis nisi nisl, ac volutpat quam mattis vitae. Sed augue massa, pulvinar sed lorem quis, pellentesque sagittis erat. Aenean venenatis ligula velit, vel viverra lorem consectetur et. Mauris sodales fringilla magna, sit amet accumsan    magna pretium in. Aliquam sagittis ante diam, in ullamcorper quam aliquam a. 
                Maecenas convallis risus non fringilla vehicula. Etiam varius diam neque. In et ipsum ac felis vestibulum venenatis vitae nec diam. Vestibulum sit amet tellus vel nisl ornare elementum id egestas nisl. Integer justo dolor, ultrices in sem ut, cursus lacinia neque. Etiam metus odio, aliquet in luctus sed, cursus vel lectus. Nulla lorem eros, finibus quis nisi in, interdum feugiat est. Nunc tempor sit amet eros id placerat. Cras viverra tempor tincidunt. Duis risus magna, vehicula et augue eu, cursus pellentesque metus.

                Vestibulum velit augue, condimentum quis massa eget, aliquet pharetra risus. Curabitur pharetra nunc in congue aliquam. Quisque vel massa at augue interdum finibus. Donec tincidunt orci quis ante egestas, sit amet porttitor augue venenatis. Donec mattis, tellus at scelerisque posuere, mauris nisi blandit libero, quis tincidunt nulla enim in tortor. Suspendisse et pulvinar urna. Nunc erat metus, commodo non accumsan quis, porttitor facilisis est. Ut dignissim erat risus, vitae pulvinar enim auctor ac.Maecenas convallis risus non fringilla vehicula. Etiam varius diam neque. In et ipsum ac felis vestibulum venenatis vitae nec diam. Vestibulum sit amet tellus vel nisl ornare elementum id egestas nisl. Integer justo dolor, ultrices in sem ut, cursus lacinia neque. Etiam metus odio, aliquet in luctus sed, cursus vel lectus. Nulla lorem eros, finibus quis nisi in, interdum feugiat est. Nunc tempor sit amet eros id placerat. Cras viverra tempor tincidunt. Duis risus magna, vehicula et augue eu, cursus pellentesque metus.

                <span className="header">Proin leo nunc molllis at</span>
                Vestibulum velit augue, condimentum quis massa eget, aliquet pharetra risus. Curabitur pharetra nunc in congue aliquam. Quisque vel massa at augue interdum finibus. Donec tincidunt orci quis ante egestas, sit amet porttitor augue venenatis. Donec mattis, tellus at scelerisque posuere, mauris nisi blandit libero, quis tincidunt nulla enim in tortor. Suspendisse et pulvinar urna. Nunc erat metus, commodo non accumsan quis, porttitor facilisis est. Ut dignissim erat risus, vitae pulvinar enim auctor ac.
                Curabitur ipsum enim, suscipit vel vestibulum sit amet, porttitor id tortor. Donec dolor arcu, elementum vulputate justo nec, congue dapibus ante. Etiam varius ut nisl quis dictum. Praesent finibus turpis massa, in ornare massa ornare pellentesque. Cras sagittis nisi nisl, ac volutpat quam mattis vitae. Sed augue massa, pulvinar sed lorem quis, pellentesque sagittis erat. Aenean venenatis ligula velit, vel viverra lorem consectetur et. Mauris sodales fringilla magna, sit amet accumsan    magna pretium in. Aliquam sagittis ante diam, in ullamcorper quam aliquam a. 
                Maecenas convallis risus non fringilla vehicula. Etiam varius diam neque. In et ipsum ac felis vestibulum venenatis vitae nec diam. Vestibulum sit amet tellus vel nisl ornare elementum id 
            </p>

        </article>
    )
}

export default ArticleText